# Generated by Django 5.2.5 on 2025-08-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PRODUCT', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PRODUCT',
            new_name='Producto',
        ),
    ]
